# Generated by Django 5.2 on 2025-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=30)),
                ('ano', models.CharField(max_length=4)),
                ('municipio', models.CharField(max_length=50)),
                ('situacao', models.CharField(max_length=50)),
                ('restricao', models.BooleanField(default=False)),
                ('data_consulta', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
